apiVersion: v1
kind: Secret
metadata:
  name: backup-username-password-secrets
  namespace: stud-for-stud-production
type: Opaque
data:
  backup-cloud-username-key: <PLACEHOLDER_SECRET>
  backup-cloud-password-key: <PLACEHOLDER_SECRET>
