apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-studforstud-production
  namespace: stud-for-stud-production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
