apiVersion: apps/v1
kind: Deployment
metadata:
  name: stud-for-stud-deadend-deployment
  namespace: stud-for-stud-development
  labels:
    app: stud-for-stud-deadend
    environment: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stud-for-stud-deadend
  template:
    metadata:
      labels:
        app: stud-for-stud-deadend
        environment: development
    spec:
      containers:
        - name: stud-for-stud-deadend
          image: harbor.chay-techs.com/deadend/fron:1.0.1
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: harbor-registry-key