apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-studforstud-development
  namespace: stud-for-stud-development
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi